package com.iohao.web2game;

import com.iohao.game.external.core.netty.simple.NettySimpleHelper;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.util.List;


// Generated by https://start.springboot.io
@SpringBootApplication
public class IoGameWeb2GameApplication {
    public static void main(String[] args) {
        SpringApplication.run(IoGameWeb2GameApplication.class, args);

        // 启动游戏服务器
        int port = 10100;
        NettySimpleHelper.run(port, List.of(new HelloLogicServer()));
    }
}
